# Generated by Django 4.2.5 on 2023-09-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='xpath',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
