# Generated by Django 4.2.5 on 2023-10-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_remove_surebets_event_remove_surebets_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surebets',
            name='oddA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_a', to='sites.odds'),
        ),
        migrations.AlterField(
            model_name='surebets',
            name='oddB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_b', to='sites.odds'),
        ),
    ]
