# Generated by Django 4.2.5 on 2023-09-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_xpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('teamA', models.CharField(max_length=50)),
                ('teamB', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SureBets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamA', models.CharField(max_length=50)),
                ('teamB', models.CharField(max_length=50)),
                ('oddA', models.FloatField()),
                ('oddB', models.FloatField()),
                ('Profit', models.FloatField()),
                ('event', models.ManyToManyField(related_name='events', to='sites.event')),
                ('site', models.ManyToManyField(related_name='sites', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='sites.event')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='sites.site')),
            ],
        ),
    ]
