# Generated by Django 4.2.5 on 2023-11-01 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_surebets_odda_alter_surebets_oddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='surebets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
