# Generated by Django 4.2.5 on 2023-09-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_event_surebets_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateField(),
        ),
    ]
