# Generated by Django 4.2.5 on 2023-09-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_event_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='date',
        ),
    ]
