# Generated by Django 4.2.5 on 2023-09-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_rename_data_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surebets',
            old_name='Profit',
            new_name='profit',
        ),
    ]
